### ISSUE TITLE
Testing every AM-Reflect interaction

### ISSUE THREAD

**Issue by AtroCty** [EarthSalamander42/dota_imba#253]
Before we roll out, realy rest every possible interactions!

**Comment by lmk1988** [comment]
Heroes tested:
- Abaddon (IMBA)
- Alchemist (IMBA)
- Ancient Apparition
- Anti Mage (IMBA)
- Arc Warden
- Axe (IMBA)
- Bane (IMBA)
- Batrider
- Beastmaster
- Bloodseeker (IMBA)
- Bounty Hunter (IMBA)
- BristleBack
- BroodMother
- Centaur (IMBA)
- Chaos Knight
- Chen
- Clinkz (IMBA)
- Clockwerk
- Crystal Maiden (IMBA)
- Dark Seer
- Dazzle (IMBA)
- Death Prophet
- Disruptor (IMBA)
- Doom and neutrals he eat
- Dragon Knight
- Drow (IMBA)
- Earth Shaker
- Earth Spirit
- Elder Titan
- Ember Spirit
- Faceless Void (IMBA)
- Pugna (IMBA)
- Tide Hunter

(Note to self: last stopped at Enchantress)

Items tested:
TODO

Errors Found
- [ ] Alchemist Greevil error
![image](https://user-images.githubusercontent.com/4424781/27009800-c7ab8b14-4ec9-11e7-897f-a522fa4d4062.png)
- [ ] Alchemist Unstable Concoction will cause AM to use the ability but has no way to throw the concoction, hence a certain self stun
- [ ] Bane Fiend's Grip error
![image](https://user-images.githubusercontent.com/4424781/27009875-71dae476-4ecb-11e7-8383-0b9b3e5ca12f.png)
- [ ] Bat Rider reflected lasso will still disarm anti mage
![image](https://user-images.githubusercontent.com/4424781/27009902-d6b569fc-4ecb-11e7-9058-6f6bbce73ba6.png)
- [ ] Reflected Clinkz's Searing arrow (manual cast) causes infinite loop but does not crash server (not suppose to be reflected I think)
![image](https://user-images.githubusercontent.com/4424781/27010118-ecd9e63c-4ecf-11e7-9114-7335e25a6a52.png)
- [ ] After reflecting Death Prophet's Spirit Siphon, Anti mage will retain the charges
![image](https://user-images.githubusercontent.com/4424781/27010286-2b6c6ba6-4ed3-11e7-8462-9346edf8ca32.png)
- [ ] Reflected Earth Spirit Boulder Smash does nothing

Unsure Interactions  (might be intended)
- [ ] If AM has aghanim, reflected spells are aghanim versions
- [ ] Chen's Test of Faith is not reflected
- [ ] Dark Seer's Ion Shell not reflected
- [ ] Disruptor's Glimpse is not reflected
- [ ] Doom's Infernal Blade is not reflected

**Comment by Shushishtok** [comment]
Very nice work! Which portion of Test of Faith is not reflected? I'm assuming the "go home bitch" portion which we made available for both teams but has no linken check since it's ally only ability in normal dota.

**Comment by Shushishtok** [comment]
>Alchemist Greevil error
> Alchemist Unstable Concoction will cause AM to use the ability but has no way to throw the concoction, hence a certain self stun

Made Spell Reflect ignore those for now.

>Bane Fiend's Grip error 

fixed.

>Bat Rider reflected lasso will still disarm anti mage

Intended, the caster of lasso disarms itself.

**Comment by Shushishtok** [comment]
>After reflecting Death Prophet's Spirit Siphon, Anti mage will retain the charges

I don't know how to solve it. Hmm.

>Reflected Earth Spirit Boulder Smash does nothing

Not sure why. It just.. doesn't.

> If AM has aghanim, reflected spells are aghanim versions

Intended.

> Chen's Test of Faith is not reflected
> Dark Seer's Ion Shell not reflected

Probably because it has no Linken's check.

> Disruptor's Glimpse is not reflected

Has no position to revert to. Disabled on Anti Mage.

> Doom's Infernal Blade is not reflected
It doesn't proc Linken's.
