### ISSUE TITLE
Move speed talents' tooltips don't make it clear that they also increase maximum move speed

### ISSUE THREAD

**Issue by fcalife** [EarthSalamander42/dota_imba#290]
Title. How to solve while keeping concise?

**Comment by NateR124** [comment]
Could make a new term like "Absolute movespeed"? Which signifies it both increases your movespeed, and your movespeed cap

**Comment by brandonsturgeon** [comment]
"+60 current and max move speed"

**Comment by fcalife** [comment]
@brandonsturgeon incredibly enough, that *is* too big. The space is pretty tight.

**Comment by AtroCty** [comment]
+60 min/max movespeed ?

**Comment by Shushishtok** [comment]
60 movespeed + max.
