### ISSUE TITLE
Self-cast on Riki buggy sometimes

### ISSUE THREAD

**Issue by AtroCty** [EarthSalamander42/dota_imba#370]
Reported by Zutch:

> Summary:  pressing the ultimate key while channeling Trick of the trade on riki with scepter cancels the channeling , which is problematic because with scepter the ult becomes target spell .
> Steps to reproduce:  get scepter, cast ult, press ult key again
> Expected Result:  not cancel the channeling
> Actual Result:  cancels ultimate channeling

**Comment by Shushishtok** [comment]
Need to rework Riki's ult.
