### ISSUE TITLE
GG System bugs

### ISSUE THREAD

**Issue by EarthSalamander42** [EarthSalamander42/dota_imba#781]
* Top bar hero overlay when gg'ed not appearing

**Comment by lintangtimur** [comment]
when player type `-gg`, showdown come out 5s, after that nothing happen.

What is the expected result for typing -gg ?

**Comment by EarthSalamander42** [comment]
An overlay should appear on the hero image in top bar (similar to when a player disconnects). If 70% of a team GG's the game ends.

**Comment by EarthSalamander42** [comment]
Fixed.
