### ISSUE TITLE
Custom game crashes during loading after the patch(?)

### ISSUE THREAD

**Issue by Kostero** [EarthSalamander42/dota_imba#857]
Today I noticed that I cannot launch the game. It crashes every time I try to load it (I can see the loading screen with the description, Patreon, and stuff, and then it crashes the whole game). Normal games and other custom games work without any issues. For some reason, the demo mode works, but 5v5 and 10v10 do not (even when I am a single person in the lobby).

Here's a console log, maybe you can find something there:
https://gist.github.com/Kostero/c901eadd8a4e33fe66bde8fe3adb719f

**Comment by Kostero** [comment]
I reinstalled the mod, rebooted the machine and validated Dota files with no effect.

**Comment by EarthSalamander42** [comment]
Hmm i don't have any Linux setup at home, i'll install one and run some tests! Unfortunately it is probably on Valve side (even though it only happens in this custom game for you) but i'll see what i can do! Can you send me a link to your steam profile for further testings together?

**Comment by Kostero** [comment]
I see. Thanks! I use the same login as here: http://steamcommunity.com/id/kostero

**Comment by lobo-tuerto** [comment]
I can confirm this.

**Comment by EarthSalamander42** [comment]
On linux as well?

**Comment by lobo-tuerto** [comment]
@EarthSalamander42 Yes, Arch based distribution (Manjaro).

**Comment by elovin** [comment]
I can also confirm this for linux

**Comment by EarthSalamander42** [comment]
Update: Valve contacted me, someone reported that issue on Dota 2's github issue tracker. We're currently working together to fix the issue. Can't give an ETA but it's being worked on.

**Comment by Kostero** [comment]
Workaround:

This issue is caused by some problems with fonts. A similar thing happens in demo mode while showing incoming damage to the dummy. The idea is as follows: we will break the fonts in demo mode, so they will be broken while loading Dota IMBA, and they won't load at all.

How we can do this?
1. Run demo mode with any hero.
2. Spawn dummy and attack it. (You can check in the console that you should get glyph errors).
3. Uninstall Microsoft fonts (`sudo apt-get remove ttf-mscorefonts-installer --purge`).
4. This should break the fonts in demo mode, check console -- there shouldn't be no more errors.
5. Launch Dota IMBA and have fun! (For safety, check first in solo lobby, or if you can watch some game.)

Please note that you probably have to do it every time. But at least I can play now.

**Comment by EarthSalamander42** [comment]
Turns out the issue was icefrog donators names written in fountains. Removed them and now linux users should be able to play Dota IMBA again!
