### ISSUE TITLE
Witch Doctor Death Ward Bug

### ISSUE THREAD

**Issue by ModderGhost** [EarthSalamander42/dota_imba#860]
Death Wards that getting spawned with killing enemy hero can survive channeling and become normal unit which allows Witch Doctor to take items from ward and sell them. This happens when its time to finish Death Ward channeling & Witch Doctor is dead.

I suspect this code:

> local units = FindUnitsInRadius(self:GetCaster():GetTeamNumber(),
> 						self:GetCaster():GetAbsOrigin(),
> 						nil,
> 						25000,
> 						DOTA_UNIT_TARGET_TEAM_FRIENDLY,
> 						DOTA_UNIT_TARGET_OTHER,
> 						DOTA_UNIT_TARGET_FLAG_INVULNERABLE,
> 						FIND_ANY_ORDER,
> 						false)

Which should be:

> local units = FindUnitsInRadius(self:GetCaster():GetTeamNumber(),
> 						**Vector(0, 0, 0)**,
> 						nil,
> 						**FIND_UNITS_EVERYWHERE**,
> 						DOTA_UNIT_TARGET_TEAM_FRIENDLY,
> 						DOTA_UNIT_TARGET_OTHER,
> 						DOTA_UNIT_TARGET_FLAG_INVULNERABLE,
> 						FIND_ANY_ORDER,
> 						false)

**Comment by EarthSalamander42** [comment]
There are high chances that the issue came from something else, i haven't heard any reports about that bug still being valid. However i've edited 25000 to FIND_UNITS_EVERYWHERE. (Vector does not matter at all when using FIND_UNITS_EVERYWHERE).

**Comment by ModderGhost** [comment]
ed

**Comment by ModderGhost** [comment]
Nope, its bug is still working
