### ISSUE TITLE
Invoker loses his globes after death

### ISSUE THREAD

**Issue by fajkoson** [EarthSalamander42/dota_imba#862]
when invoker dies, he has initialy only 2 globes arrnoud himself instead of 3 so he cant invoke any spell. Ingame fix, you have to recast different type of globe, if you cast the same type , maximum will be still 2.
--
Edit1: not able to reproduce while killed by roshan, will try to observe while ingame. Maybe some debuff needs to be active on invoker at time of death.

**Comment by EarthSalamander42** [comment]
Pushed a bunch of fixes for Invoker the last weeks, probably fixed it. If not feel free to open a new issue.
