### ISSUE TITLE
stackable tangos

### ISSUE THREAD

**Issue by fajkoson** [EarthSalamander42/dota_imba#873]
Tangos effectg is stackable.. so you are able to get 100 stacks with no big deal.. its being abbused hard way.
Expiration of previous tango is reseted by the new (eaten-one). Basicaly you eat tangos foreva you have money or you are perma stuned or die.

https://imgur.com/a/WaD2eLh

**Comment by sercankd** [comment]
Eating vegan is better, checkmate carnivores

**Comment by fajkoson** [comment]
fixed
